version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: handmade
      MYSQL_USER: long
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - wp-network

  wordpress:
    image: wordpress:php7.4-apache
    container_name: wordpress
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: handmade
      WORDPRESS_DB_USER: long
      WORDPRESS_DB_PASSWORD: 123456
    volumes:
      - ./wp-data:/var/www/html
    expose:
      - "80"
    networks:
      - wp-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/archive/craftedelegance.site:/etc/ssl/certs/archive:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./custom_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wp-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 1d; done"
    networks:
      - wp-network

networks:
  wp-network:
